# Numpy

1) 벡터 및 행렬 연산에 특화된 라이브러리<br>
2) array 단위로 데이터를 관리함, 행렬(matrix)와 비슷함<br>
3) pandas와 함께 데이터분석에 많이 사용됨<br>

In [1]:
# 넘파이 모듈을 import
import numpy as np

In [2]:
# 리스트
data1 = [1, 2, 3, 4, 5]
# 리스트를 넘파이 배열로 변환
arr1 = np.array(data1)
print(arr1)
print(type(arr1)) # 자료형
print(arr1.shape) # 배열의 차원

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
# 2차원 리스트
data2 = [[1,2,3], [4,5,6]]
# 2차원 리스트를 넘파이의 2차원 행렬로 변환
arr2 = np.array(data2)
print(arr2)
print(arr2.shape)
# (2,3) => 2행 3열의 2차원 행렬

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
# 2차원 행렬
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [5]:
arr1 + arr2 # 같은 자리의 값을 계산

array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [7]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [8]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [9]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
arr1 ** 2 # 거듭제곱

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
# 배열의 인덱싱
# 스트링 리스트를 넘파이 배열로 변환
names = np.array(\
["김철수", "이승호", "박철호", "김철수", "홍성민", "마이클", "존"])
# 7행 4열의 난수 발생, randn 정규분포 난수
data = np.random.randn(7, 4)

In [12]:
names

array(['김철수', '이승호', '박철호', '김철수', '홍성민', '마이클', '존'], dtype='<U3')

In [13]:
data

array([[ 0.22798933,  0.03175973,  0.55451583, -0.36167055],
       [ 0.17562178, -0.25295708,  0.49247334,  1.33589128],
       [-3.62877152, -0.72768227, -0.30161807,  1.95674674],
       [-0.38348647,  0.58693698,  1.49198506, -0.47490651],
       [ 0.98342312, -1.14048313, -0.37991613,  0.55444362],
       [ 1.27431712, -1.30394177,  0.36568125, -0.17293602],
       [ 0.49771176,  0.1315803 ,  0.41853082, -1.98835464]])

In [14]:
x = np.random.randn(8)
y = np.random.randn(8)

In [15]:
x

array([ 0.77905146, -1.19573803,  0.24971482, -0.13185305, -1.18093652,
       -0.87268326, -0.74794339, -0.22614987])

In [16]:
y

array([-0.37772256, -1.34794617, -1.01025698,  1.94818228,  0.43956061,
       -2.09432071, -0.64688684, -0.53345901])

In [17]:
# 각 배열의 자리수를 비교해 큰 값을 뽑아서 새로운 배열을 생성함
np.maximum(x, y)

array([ 0.77905146, -1.19573803,  0.24971482,  1.94818228,  0.43956061,
       -0.87268326, -0.64688684, -0.22614987])

In [18]:
# 5행 4열의 랜덤값 생성
arr = np.random.randn(5, 4)
arr

array([[-1.01819298, -0.65123687,  1.28965633,  0.50839385],
       [ 2.09237088, -0.06962041,  0.49990652,  1.6855924 ],
       [ 0.12086384,  0.31138696, -1.27208386, -1.3138284 ],
       [ 0.99225015,  0.67206967, -1.58920002,  0.35656373],
       [ 0.71877318,  0.07541299,  0.64198364,  0.27360505]])

In [19]:
# 전체 합계
arr.sum()

4.324666670347837

In [20]:
# 전체 평군
arr.mean()

0.21623333351739188

In [21]:
# 각 열의 합계
arr.sum(axis=0)

array([ 2.90606508,  0.33801234, -0.42973739,  1.51032663])

In [22]:
# 각 행의 합계
arr.sum(axis=1)

array([ 0.12862033,  4.2082494 , -2.15366145,  0.43168353,  1.70977486])

In [23]:
# 오름차순 정렬
np.sort(arr)

array([[-1.01819298, -0.65123687,  0.50839385,  1.28965633],
       [-0.06962041,  0.49990652,  1.6855924 ,  2.09237088],
       [-1.3138284 , -1.27208386,  0.12086384,  0.31138696],
       [-1.58920002,  0.35656373,  0.67206967,  0.99225015],
       [ 0.07541299,  0.27360505,  0.64198364,  0.71877318]])

In [24]:
# 내림차순 정렬(열을 기준으로)
np.sort(arr, axis=0)[::-1]

array([[ 2.09237088,  0.67206967,  1.28965633,  1.6855924 ],
       [ 0.99225015,  0.31138696,  0.64198364,  0.50839385],
       [ 0.71877318,  0.07541299,  0.49990652,  0.35656373],
       [ 0.12086384, -0.06962041, -1.27208386,  0.27360505],
       [-1.01819298, -0.65123687, -1.58920002, -1.3138284 ]])

In [25]:
names = np.array(\
["김철수", "이승호", "박철호", "김철수", "홍성민", "마이클", "존"])
ages = np.array([20, 25, 20, 23, 28, 29, 30, 31, 30, 40, 45])
# 중복값을 제거한 결과 출력
print(np.unique(names))
print(len(np.unique(names)))

['김철수' '마이클' '박철호' '이승호' '존' '홍성민']
6


In [26]:
np.unique(ages)

array([20, 23, 25, 28, 29, 30, 31, 40, 45])

In [27]:
# 영화 평점 데이터 로딩
# loadtxt() : 텍스트 파일 로딩, delimiter : 필드 구분자, dtype : 자료형
data = np.loadtxt("./data/movie_data/ratings.dat", delimiter="::", dtype=np.int64)

In [28]:
# 데이터의 첫 5행만 확인
# [행start:end, 열start:end]
data[:5, :] # data[:5,]와 같음

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [29]:
# 데이터의 형태 확인
# (행, 열)
data.shape

(1000209, 4)

In [30]:
# 전체 평균 평점 계산
# 행범위:열범위
# data[:,2] : 전체행, 2번열
mean_rating_total = data[:,2].mean() # rating 컬럼
mean_rating_total

3.581564453029317

In [31]:
# 사용자 아이디 수집
user_ids = np.unique(data[:,0]) # 전체행, 0번열
print(user_ids)
print(len(user_ids))

[   1    2    3 ... 6038 6039 6040]
6040


In [32]:
# 사용자별 평균값을 저장할 배열
mean_values = []
for user_id in user_ids:
    # 첫번째 열이 아이디
    # 예를 들어 현재 user_id가 1이라면 user_id가 1인 행들만 추출해서
    # data_for_user에 저장
    # data 중에서 모든행, 0번필드가 user_id인 행의 모든 컬럼
    data_for_user = data[data[:,0] == user_id, :]
    # 2번째 인덱스(평점)에 해당하는 값의 평균값
    value = data_for_user[:, 2].mean()
    # 사용자아이디와 평균값을 배열에 추가
    # 리스트 안에 리스트가 들어가므로 2차원 리스트로 만들어짐
    mean_values.append([user_id, value])

In [33]:
# 사용자 아이디별 평점 확인
print(mean_values[:5])
print(len(mean_values))

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
6040


In [34]:
# 리스트를 넘파이 배열로 변환
mean_array = np.array(mean_values, dtype=np.float32)

In [35]:
mean_array[:5] # 0번행부터 4번행까지

array([[1.       , 4.188679 ],
       [2.       , 3.7131784],
       [3.       , 3.9019608],
       [4.       , 4.1904764],
       [5.       , 3.1464646]], dtype=float32)

In [36]:
mean_array.shape

(6040, 2)

In [37]:
# 계산 결과를 csv 파일로 저장
np.savetxt("./data/movie_data/result.csv",\
          mean_array, fmt="%.1f", delimiter=",")
